---
# tasks file for kibana

      - name: Check that the Kibana tgz exists
        stat:
          path: /tmp/kibana-{{ elastic_version }}-linux-x86_64.tar.gz
        register: kstat_result
        tags: kibana

      - name: Upload tar.gz Kiban from remote URL
        get_url:
          url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ elastic_version }}-linux-x86_64.tar.gz"
          dest: "/tmp/kibana-{{ elastic_version }}-linux-x86_64.tar.gz"
          mode: 0755
          timeout: 60
          force: true
        register: get_kibana
        until: get_kibana is succeeded
        when: not kstat_result.stat.exists
        tags: kibana

      - name: Create directrory for Kibana
        file:
          state: directory
          path: "{{ kibana_home }}"
        tags: kibana

      - name: Extract Kibana in the installation directory
        become: true
        unarchive:
          copy: false
          src: "/tmp/kibana-{{ elastic_version }}-linux-x86_64.tar.gz"
          dest: "{{ kibana_home }}"
          extra_opts: [--strip-components=1]
          creates: "{{ kibana_home }}/bin/kibana"
        tags:
          - skip_ansible_lint
          - kibana
        
      - name: Setup Kibana config
        become: yes
        template:
          src: templates/kibana.yml.j2
          dest: "{{ kibana_home }}/config/kibana.yml"
        tags: elastic
     